name: protoshop-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_LOCATION: ProtoshopBackend.csproj
  ELASTIC_BEANSTALK_NAME: protoshop
  ELASTIC_BEANSTALK_ENV_NAME: Protoshop-env-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Setup EB config
      run: |
        mkdir -p .ebextensions
        echo "option_settings:
          aws:autoscaling:launchconfiguration:
            InstanceType: t2.micro
          aws:elasticbeanstalk:container:dotnet:
            Runtime: net-8.0" > .ebextensions/options.config
    
    - name: Restore dependencies
      run: dotnet restore $PROJECT_LOCATION
    
    - name: Build
      run: dotnet build --no-restore $PROJECT_LOCATION
    
    - name: Pack
      run: |
        dotnet publish $PROJECT_LOCATION -c Release --output "${{ github.workspace }}/publish"
        cd "${{ github.workspace }}/publish"
        cp -r ../.ebextensions .
        zip -r ../${{github.run_id}}.zip .
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: deploy-files
        path: ${{github.run_id}}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4.1.7
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Deploy
      run: |
        aws s3 cp "deploy-files/${{github.run_id}}.zip" s3://elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/protoshop-backend/
        aws elasticbeanstalk create-application-version \
          --application-name $ELASTIC_BEANSTALK_NAME \
          --version-label ${{github.run_id}} \
          --description ${{github.run_id}} \
          --source-bundle S3Bucket="elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/protoshop-backend/${{github.run_id}}.zip"
        aws elasticbeanstalk update-environment \
          --application-name $ELASTIC_BEANSTALK_NAME \
          --environment-name $ELASTIC_BEANSTALK_ENV_NAME \
          --version-label ${{github.run_id}} \
          --option-settings \
            Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=aws-elasticbeanstalk-ec2-role
        aws elasticbeanstalk wait environment-updated \
          --application-name $ELASTIC_BEANSTALK_NAME \
          --environment-name $ELASTIC_BEANSTALK_ENV_NAME
