name: protoshop-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_LOCATION: ProtoshopBackend.csproj
  ELASTIC_BEANSTALK_NAME: protoshop-backend
  ELASTIC_BEANSTALK_ENV_NAME: protoshop-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore $PROJECT_LOCATION

      - name: Build
        run: dotnet build --no-restore $PROJECT_LOCATION

      - name: Create .ebextensions
        run: |
          mkdir -p .ebextensions
          cat > .ebextensions/alb-https.config << 'EOL'
          option_settings:
            aws:elbv2:listener:443:
              ListenerEnabled: 'true'
              Protocol: HTTPS
              SSLCertificateArns: arn:aws:acm:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:certificate/${{ secrets.SSL_CERTIFICATE_ID }}
            
            # Redirect HTTP to HTTPS
            aws:elbv2:listener:80:
              ListenerEnabled: 'true'
              DefaultProcess: default
              Rules: httpsredirect
            
            # Rule for HTTP to HTTPS redirect
            aws:elbv2:listenerrule:httpsredirect:
              PathPatterns: /*
              Process: redirecthttps
            
            # Process for HTTP to HTTPS redirect
            aws:elasticbeanstalk:environment:process:redirecthttps:
              Port: '80'
              Protocol: HTTP
              HealthCheckPath: /
              MatcherHTTPCode: 200
              RedirectConfig:
                Host: '#{host}'
                Path: '/#{path}'
                Port: '443'
                Protocol: HTTPS
                Query: '#{query}'
                StatusCode: HTTP_301
          EOL

      - name: Pack
        run: |
          dotnet publish $PROJECT_LOCATION -c Release -o "${{ github.workspace }}/${{github.run_id}}/net8.0"
          echo "web: dotnet /var/app/current/net8.0/ProtoshopBackend.dll" > "${{ github.workspace }}/${{github.run_id}}/Procfile"
          mkdir -p "${{ github.workspace }}/${{github.run_id}}/.ebextensions"
          cp -r .ebextensions/* "${{ github.workspace }}/${{github.run_id}}/.ebextensions/"
          cd ${{github.run_id}}
          zip -r ../${{github.run_id}}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: deploy-files
          path: ${{github.run_id}}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: deploy-files

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        run: |
          aws s3 cp "${{github.run_id}}.zip" s3://elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/protoshop-backend/
          aws elasticbeanstalk create-application-version \
            --application-name $ELASTIC_BEANSTALK_NAME \
            --version-label ${{github.run_id}} \
            --description ${{github.run_id}} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/protoshop-backend/${{github.run_id}}.zip"
          aws elasticbeanstalk update-environment \
            --application-name $ELASTIC_BEANSTALK_NAME \
            --environment-name $ELASTIC_BEANSTALK_ENV_NAME \
            --version-label ${{github.run_id}}
          aws elasticbeanstalk wait environment-updated \
            --application-name $ELASTIC_BEANSTALK_NAME \
            --environment-name $ELASTIC_BEANSTALK_ENV_NAME